### ISSUE TITLE
Add movie top lists features

### ISSUE THREAD

**Issue by Maxim-Zavidei** [Maxim-Zavidei/viauc-sep6-s23#28]
# Sub-tasks:
- [x] Create TopLists models
- [x] Update database models
- [x] Create component for seeing top lists
- [x] Create repository methods for getting and adding top lists
- [x] Create back-end endpoints for getting and adding top lists
- [x] Modify the card to have a button to add the movie to top list

**Comment by Maxim-Zavidei** [comment]
merged
