### ISSUE TITLE
Dockerize the whole aplication.

### ISSUE THREAD

**Issue by LilianBittar** [Maxim-Zavidei/viauc-sep6-s23#5]
# Sub-tasks: 
- [x] Created .dockerignore.
- [x]  Created Docker file in the .NET application. 
- [x] Docker file must include an environment to build .NET 7 application and the base final image must include only the run time for :NET.
- [x] Docker file must also include node.js in the build stage to be able to compile the angular app.
- [x] Add a capRover file with the path to the docker file.
