### ISSUE TITLE
Add github workflow files for CI/CD

### ISSUE THREAD

**Issue by Maxim-Zavidei** [Maxim-Zavidei/viauc-sep6-s23#6]
# Sub-tasks:
- [ ] Create a workflow for the dev branch to build and test both the Angular and .NET applications
- [ ] Create a workflow file for the main (production) branch to build and test both the Angular and .NET applications.
- [ ] Setup caprover on the dedicated server to pull the main branch of the github repo whenever there is a new realease
